In [1]:
import pandas as pd
from google_play_scraper import reviews, Sort

In [2]:
apps = {
    "CBE": "com.combanketh.mobilebanking",
    "BOA": "com.boa.boaMobileBanking",
    "Dashen": "com.dashen.dashensuperapp"
}

In [3]:
all_reviews = []

In [4]:
for bank, app_id in apps.items():

    print(f"Scraping reviews for {bank}...")

    result, continuation_token = reviews(
        app_id,
        lang='en',
        country='et',
        sort=Sort.NEWEST,
        count=500
    )

    for review in result:

        all_reviews.append({
            "review_id": review["reviewId"],
            "review": review["content"],
            "rating": review["score"],
            "date": review["at"],
            "bank": bank,
            "source": "Google Play"
        })

print("Scraping completed.")

Scraping reviews for CBE...
Scraping reviews for BOA...
Scraping reviews for Dashen...
Scraping completed.

In [5]:
df = pd.DataFrame(all_reviews)

In [6]:
df.head()

,review_id,review,rating,date,bank,source
0,377120dd-1d3e-47ad-a715-c0a538c5d33f,IT'S NOT WORK ON HUAWEI DEVICES,4,2026-05-15 12:07:21,CBE,Google Play
1,46357e27-661d-4136-bf66-ca7bb91e1427,wow,4,2026-05-14 18:52:51,CBE,Google Play
2,bfc27568-1471-4937-934f-e5325ea96f46,nice app,5,2026-05-14 18:28:23,CBE,Google Play
3,9d8ba9a5-4899-4af9-bef1-f12a5dfd7f3a,formative,5,2026-05-14 16:49:46,CBE,Google Play
4,07dea887-2fcf-446c-ac8d-753be7c90256,best app for financial activities 🙌,5,2026-05-14 16:46:29,CBE,Google Play

In [7]:
df.tail ()

,review_id,review,rating,date,bank,source
1495,35fc8b13-0a39-4237-b28d-39904b57f125,good,5,2025-08-14 16:14:19,Dashen,Google Play
1496,5043e566-8cbc-4384-9382-8d929065614e,There are plenty of features missed e. g elect...,2,2025-08-14 15:16:24,Dashen,Google Play
1497,0269ed2c-74ca-4b44-8226-0a664489ac78,የሶፍትዌሩ ለአጠቃቀም ምቹና ቀላል መሆኑ ተመራጭ ያደርገዋል,5,2025-08-14 13:56:25,Dashen,Google Play
1498,9a553128-a2f5-4c25-8c0c-abc680033d42,በጣም ችግር አለበት,1,2025-08-14 12:45:15,Dashen,Google Play
1499,069eb4b6-e778-4b5c-b6bd-1e5dea63844e,best,5,2025-08-14 11:27:00,Dashen,Google Play

In [8]:
df.shape

(1500, 6)

In [10]:
df["bank"].value_counts()

bank
CBE       500
BOA       500
Dashen    500
Name: count, dtype: int64

In [11]:
df.to_csv("../data/raw/raw_reviews.csv", index=False)

In [12]:
df.isnull().sum()

review_id    0
review       0
rating       0
date         0
bank         0
source       0
dtype: int64

In [13]:
df = df.dropna(subset=["review", "rating"])

In [14]:
df = df.drop_duplicates(subset="review_id")

In [15]:
df["date"] = pd.to_datetime(df["date"]).dt.strftime("%Y-%m-%d")

In [16]:
df.head()

,review_id,review,rating,date,bank,source
0,377120dd-1d3e-47ad-a715-c0a538c5d33f,IT'S NOT WORK ON HUAWEI DEVICES,4,2026-05-15,CBE,Google Play
1,46357e27-661d-4136-bf66-ca7bb91e1427,wow,4,2026-05-14,CBE,Google Play
2,bfc27568-1471-4937-934f-e5325ea96f46,nice app,5,2026-05-14,CBE,Google Play
3,9d8ba9a5-4899-4af9-bef1-f12a5dfd7f3a,formative,5,2026-05-14,CBE,Google Play
4,07dea887-2fcf-446c-ac8d-753be7c90256,best app for financial activities 🙌,5,2026-05-14,CBE,Google Play

In [17]:
df.tail()

,review_id,review,rating,date,bank,source
1495,35fc8b13-0a39-4237-b28d-39904b57f125,good,5,2025-08-14,Dashen,Google Play
1496,5043e566-8cbc-4384-9382-8d929065614e,There are plenty of features missed e. g elect...,2,2025-08-14,Dashen,Google Play
1497,0269ed2c-74ca-4b44-8226-0a664489ac78,የሶፍትዌሩ ለአጠቃቀም ምቹና ቀላል መሆኑ ተመራጭ ያደርገዋል,5,2025-08-14,Dashen,Google Play
1498,9a553128-a2f5-4c25-8c0c-abc680033d42,በጣም ችግር አለበት,1,2025-08-14,Dashen,Google Play
1499,069eb4b6-e778-4b5c-b6bd-1e5dea63844e,best,5,2025-08-14,Dashen,Google Play

In [18]:
clean_df = df[["review", "rating", "date", "bank", "source"]]

In [19]:
clean_df.head()

                                review  rating        date bank       source
0      IT'S NOT WORK ON HUAWEI DEVICES       4  2026-05-15  CBE  Google Play
1                                  wow       4  2026-05-14  CBE  Google Play
2                             nice app       5  2026-05-14  CBE  Google Play
3                            formative       5  2026-05-14  CBE  Google Play
4  best app for financial activities 🙌       5  2026-05-14  CBE  Google Play

In [20]:
clean_df.tail()

,review,rating,date,bank,source
1495,good,5,2025-08-14,Dashen,Google Play
1496,There are plenty of features missed e. g elect...,2,2025-08-14,Dashen,Google Play
1497,የሶፍትዌሩ ለአጠቃቀም ምቹና ቀላል መሆኑ ተመራጭ ያደርገዋል,5,2025-08-14,Dashen,Google Play
1498,በጣም ችግር አለበት,1,2025-08-14,Dashen,Google Play
1499,best,5,2025-08-14,Dashen,Google Play

In [21]:
clean_df.shape

(1500, 5)

In [22]:
missing_percentage = clean_df.isnull().mean() * 100
missing_percentage

review    0.0
rating    0.0
date      0.0
bank      0.0
source    0.0
dtype: float64

In [23]:
clean_df.to_csv("../data/raw/clean_reviews.csv", index=False)