In [10]:
import pandas as pd

from sqlalchemy import create_engine

In [13]:
df = pd.read_csv("../data/raw/final_processed_reviews.csv")

In [14]:
df.head()

,review,rating,date,bank,source,sentiment_label,sentiment_score,cleaned_review,identified_theme
0,IT'S NOT WORK ON HUAWEI DEVICES,4,2026-05-15,CBE,Google Play,negative,0.999691,work huawei device,General Experience
1,wow,4,2026-05-14,CBE,Google Play,positive,0.999592,wow,General Experience
2,nice app,5,2026-05-14,CBE,Google Play,positive,0.999806,nice app,General Experience
3,formative,5,2026-05-14,CBE,Google Play,positive,0.998885,formative,General Experience
4,best app for financial activities 🙌,5,2026-05-14,CBE,Google Play,positive,0.996808,good app financial activity,General Experience

In [16]:
banks_df = pd.DataFrame({
    'bank_id': [1, 2, 3],
    'bank_name': [
        'Commercial Bank of Ethiopia',
        'Bank of Abyssinia',
        'Dashen Bank'
    ],
    'app_name': [
        'CBE Mobile',
        'BOA Mobile',
        'Dashen Super App'
    ]
})

In [17]:
bank_mapping = {
    'CBE': 1,
    'BOA': 2,
    'Dashen': 3
}

df['bank_id'] = df['bank'].map(bank_mapping)

In [18]:
df.head()

,review,rating,date,bank,source,sentiment_label,sentiment_score,cleaned_review,identified_theme,bank_id
0,IT'S NOT WORK ON HUAWEI DEVICES,4,2026-05-15,CBE,Google Play,negative,0.999691,work huawei device,General Experience,1
1,wow,4,2026-05-14,CBE,Google Play,positive,0.999592,wow,General Experience,1
2,nice app,5,2026-05-14,CBE,Google Play,positive,0.999806,nice app,General Experience,1
3,formative,5,2026-05-14,CBE,Google Play,positive,0.998885,formative,General Experience,1
4,best app for financial activities 🙌,5,2026-05-14,CBE,Google Play,positive,0.996808,good app financial activity,General Experience,1

In [19]:
reviews_df = df[[
    'bank_id',
    'review',
    'rating',
    'date',
    'sentiment_label',
    'sentiment_score',
    'identified_theme',
    'source'
]]

In [20]:
reviews_df.columns = [
    'bank_id',
    'review_text',
    'rating',
    'review_date',
    'sentiment_label',
    'sentiment_score',
    'identified_theme',
    'source'
]

In [21]:
df.head()

,review,rating,date,bank,source,sentiment_label,sentiment_score,cleaned_review,identified_theme,bank_id
0,IT'S NOT WORK ON HUAWEI DEVICES,4,2026-05-15,CBE,Google Play,negative,0.999691,work huawei device,General Experience,1
1,wow,4,2026-05-14,CBE,Google Play,positive,0.999592,wow,General Experience,1
2,nice app,5,2026-05-14,CBE,Google Play,positive,0.999806,nice app,General Experience,1
3,formative,5,2026-05-14,CBE,Google Play,positive,0.998885,formative,General Experience,1
4,best app for financial activities 🙌,5,2026-05-14,CBE,Google Play,positive,0.996808,good app financial activity,General Experience,1

In [26]:
engine = create_engine(
    "postgresql://new@localhost:5432/bank_reviews"
)

In [27]:
banks_df.to_sql(
    'banks',
    engine,
    if_exists='replace',
    index=False
)

3

In [28]:
reviews_df.to_sql(
    'reviews',
    engine,
    if_exists='replace',
    index=True,
    index_label='review_id'
)

500